# Generated by Django 4.0.1 on 2022-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('Contact', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
            ],
        ),
    ]
